# Form implementation generated from reading ui file 'c:\Users\ivang\OneDrive\Рабочий стол\Python prog\pyqt6\Scripts\PythonCasino777.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CasinoGame(object):
    def setupUi(self, CasinoGame):
        CasinoGame.setObjectName("CasinoGame")
        CasinoGame.setEnabled(True)
        CasinoGame.resize(353, 182)
        CasinoGame.setMouseTracking(False)
        self.pushButton = QtWidgets.QPushButton(CasinoGame)
        self.pushButton.setGeometry(QtCore.QRect(10, 150, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(CasinoGame)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 150, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(CasinoGame)
        self.label.setGeometry(QtCore.QRect(60, 10, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CasinoGame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(80, 50, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CasinoGame)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(160, 50, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(CasinoGame)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(240, 50, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(CasinoGame)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(100, 130, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(CasinoGame)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 150, 171, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(CasinoGame)
        QtCore.QMetaObject.connectSlotsByName(CasinoGame)

    def retranslateUi(self, CasinoGame):
        _translate = QtCore.QCoreApplication.translate
        CasinoGame.setWindowTitle(_translate("CasinoGame", "Dialog"))
        self.pushButton.setText(_translate("CasinoGame", "Крутить"))
        self.pushButton_2.setText(_translate("CasinoGame", "Выход"))
        self.label.setText(_translate("CasinoGame", "СЧАСТЛИВАЯ СЕМЁРКА"))
        self.label_2.setText(_translate("CasinoGame", "?"))
        self.label_3.setText(_translate("CasinoGame", "?"))
        self.label_4.setText(_translate("CasinoGame", "?"))
        self.label_5.setText(_translate("CasinoGame", "Процент выигрыша"))
        self.pushButton_3.setText(_translate("CasinoGame", "Правила игры"))
